export const FETCH_COIN_DATA = 'FETCH_COIN_DATA';
export const FETCH_COIN_DATA_SUCCESS = 'FETCH_COIN_DATA_SUCCESS';

export const FETCH_CHART_DATA = 'FETCH_CHART_DATA';
export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';

export const SELECTED_COIN = 'SELECTED_COIN';
